# Generated by Django 5.1.6 on 2025-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=100)),
                ('campo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=100)),
                ('poder', models.IntegerField()),
            ],
        ),
    ]
