# Generated by Django 5.1.6 on 2025-03-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
    ]
