# Generated by Django 5.1.6 on 2025-03-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0002_usuarios_apellido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menus',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
