# Generated by Django 5.1.6 on 2025-03-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mi_admin', '0003_delete_menus_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='alimentos_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_alimentos', models.IntegerField()),
                ('ensaladas_nombre', models.CharField(max_length=20)),
                ('vegetales_nombre', models.CharField(max_length=20)),
                ('postres_nombre', models.CharField(max_length=20)),
                ('bebidas_nombre', models.CharField(max_length=20)),
                ('carnes_nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='planes_alimenticios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_fit', models.CharField()),
                ('plan_normal', models.CharField()),
                ('plan_vegetariano', models.CharField()),
                ('plan_vegano', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('numero_id', models.IntegerField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.usuarios')),
            ],
        ),
    ]
