# Generated by Django 5.1.6 on 2025-03-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos_menu',
            name='bebidas_nombre',
        ),
        migrations.RemoveField(
            model_name='alimentos_menu',
            name='carnes_nombre',
        ),
        migrations.RemoveField(
            model_name='alimentos_menu',
            name='ensaladas_nombre',
        ),
        migrations.RemoveField(
            model_name='alimentos_menu',
            name='postres_nombre',
        ),
        migrations.RemoveField(
            model_name='alimentos_menu',
            name='vegetales_nombre',
        ),
        migrations.RemoveField(
            model_name='planes_alimenticios',
            name='plan_fit',
        ),
        migrations.RemoveField(
            model_name='planes_alimenticios',
            name='plan_normal',
        ),
        migrations.RemoveField(
            model_name='planes_alimenticios',
            name='plan_vegano',
        ),
        migrations.RemoveField(
            model_name='planes_alimenticios',
            name='plan_vegetariano',
        ),
        migrations.AddField(
            model_name='alimentos_menu',
            name='carbohidratos_menu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentos_menu',
            name='ensaldas_menu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentos_menu',
            name='grasas_menu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentos_menu',
            name='proteina_menu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planes_alimenticios',
            name='descripcion_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes_alimenticios',
            name='precio_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='planes_alimenticios',
            name='tipo_plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alimentos_menu',
            name='num_alimentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero_id',
            field=models.IntegerField(),
        ),
    ]
