# Generated by Django 5.1.6 on 2025-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0005_remove_alimentos_menu_bebidas_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='nombre_menu',
            field=models.CharField(max_length=40),
        ),
    ]
