# Generated by Django 5.1.6 on 2025-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0007_alter_menus_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='correo_electronico',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
