# Generated by Django 5.1.6 on 2025-03-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0008_rename_correo_electronico_usuarios_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='correo',
            new_name='correo_electronico',
        ),
    ]
