# Generated by Django 5.1.6 on 2025-03-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0009_rename_password_usuarios_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('administrativo', 'Administrativo'), ('empleado', 'Empleado')], default='cliente', max_length=20)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.usuarios')),
            ],
        ),
    ]
