# Generated by Django 5.1.6 on 2025-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0012_reserva_delete_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero_id',
            field=models.IntegerField(max_length=30),
        ),
    ]
