# Generated by Django 5.1.6 on 2025-04-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0014_alter_reserva_options_remove_reserva_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
