# Generated by Django 5.1.6 on 2025-04-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0015_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mi_admin.menus'),
            preserve_default=False,
        ),
    ]
