# Generated by Django 5.1.6 on 2025-04-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0016_reserva_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('edad', models.IntegerField()),
                ('actividad_fisica', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.usuarios')),
            ],
        ),
    ]
