# Generated by Django 5.1.6 on 2025-04-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0019_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_aleatorio',
            field=models.IntegerField(default=0),
        ),
    ]
