# Generated by Django 5.1.6 on 2025-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0020_reserva_numero_aleatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero_id',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
