# Generated by Django 5.1.6 on 2025-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0021_alter_usuarios_numero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
